require:
  - rubocop/cop/internal_affairs
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
    - "bin/*"
    - "Rakefile"
    - "config.ru"
    - "vendor/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "node_modules/**/*"
    - "Gemfile.lock"
    - ".rubocop.yml"
    - "db/schema.rb"

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/NumericPredicate:
  Exclude:
    - "spec/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120
Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20

Bundler/OrderedGems:
  Enabled: false
