require:
  - rubocop/cop/internal_affairs
  - rubocop-rails
  - rubocop-rspec
  - rubocop-performance

AllCops:
  TargetRubyVersion: 2.7.1
  NewCops: enable
  Exclude:
    - "bin/*"
    - "Rakefile"
    - "config.ru"
    - "vendor/**/*"
    - "tmp/**/*"
    - ".git/**/*"
    - "node_modules/**/*"
    - "Gemfile.lock"
    - ".rubocop.yml"
    - "db/schema.rb"
    - "config/environments/**/*"

Style/Documentation:
  Enabled: false
Style/StringLiterals:
  Enabled: false
Style/NumericPredicate:
  Exclude:
    - "spec/**/*"
Style/FrozenStringLiteralComment:
  Enabled: false

Layout/LineLength:
  Max: 120

Metrics/MethodLength:
  Max: 20
Metrics/AbcSize:
  Max: 20
Metrics/BlockLength:
  Max: 25
  Exclude:
    - "spec/**/*"
Bundler/OrderedGems:
  Enabled: false

RSpec/Capybara/FeatureMethods:
  Enabled: false
RSpec/MultipleExpectations:
  Enabled: false
RSpec/ExampleLength:
  Max: 10
RSpec/NestedGroups:
  Max: 5
RSpec/ExampleLength:
  Max: 15
